import { Card, CardContent, CardHeader, CardTitle } from "../core/Card";
import { AlertTriangle, CheckCircle, Info } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../core/Button";

interface RiskAssessmentProps {
  riskLevel: "LOW" | "MODERATE" | "HIGH";
  confidence: number;
}

export function RiskAssessmentWidget({
  riskLevel,
  confidence,
}: RiskAssessmentProps) {
  const getRiskColor = () => {
    switch (riskLevel) {
      case "HIGH":
        return "text-status-danger bg-red-50 border-red-200";
      case "MODERATE":
        return "text-status-warning bg-yellow-50 border-yellow-200";
      case "LOW":
        return "text-status-safe bg-green-50 border-green-200";
    }
  };

  const getRiskIcon = () => {
    switch (riskLevel) {
      case "HIGH":
        return <AlertTriangle className="h-10 w-10 text-status-danger mb-3" />;
      case "MODERATE":
        return <Info className="h-10 w-10 text-status-warning mb-3" />;
      case "LOW":
        return <CheckCircle className="h-10 w-10 text-status-safe mb-3" />;
    }
  };

  return (
    <Card className="w-full">
      <CardHeader className="bg-slate-50 border-b border-surface-border rounded-t-xl">
        <CardTitle>Automated Risk Assessment</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 pt-6">
        <div
          className={`p-8 rounded-xl border flex flex-col items-center justify-center text-center ${getRiskColor()}`}
        >
          {getRiskIcon()}
          <h2 className="text-3xl font-bold mb-1 tracking-tight">
            {riskLevel} RISK DETECTED
          </h2>
          <p className="text-sm opacity-80 font-medium">
            AI Diagnostic Confidence: {confidence}%
          </p>
        </div>

        <div className="bg-surface-muted p-5 rounded-lg text-sm text-slate-700 border border-slate-200">
          <p className="font-semibold mb-2 text-slate-900">
            Clinical Disclaimer
          </p>
          <p>
            This assessment is a preliminary triage output generated by an AI
            model. It does not constitute a definitive medical diagnosis. Based
            on the visual characteristics, we strongly recommend booking a brief
            consultation for secondary clinical review by a certified
            dermatologist.
          </p>
        </div>

        <Link to="/patient/consultation" className="block w-full">
          <Button className="w-full text-base py-6">
            Book Doctor Consultation
          </Button>
        </Link>
      </CardContent>
    </Card>
  );
}
